apiVersion: v1
kind: Service
metadata:
  name: {{ include "databunker-demo.fullname" . }}
  labels:
    {{- include "databunker-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePort)) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "databunker-demo.selectorLabels" . | nindent 4 }}
