{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    helm.sh/resource-policy: keep
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace ( include "common.names.fullname" .) ) }}

  {{- $databunkerMasterkey := "" }}
  {{- if $secret }}
    {{- if index $secret.data "databunker-masterkey" }}
      {{- $databunkerMasterkey = index $secret.data "databunker-masterkey" }}
    {{- end }}
  {{- end }}
  {{- if not $databunkerMasterkey }}
    {{- if .Values.databunkerMasterkey }}
      {{- $databunkerMasterkey = .Values.databunkerMasterkey | b64enc | quote }}
    {{- else }}
      {{- $databunkerMasterkey = substr 1 49 (printf "%x%x%x%x%x%x" (int64 (randNumeric 18)) (int64 (randNumeric 18)) (int64 (randNumeric 18)) (int64 (randNumeric 18)) (int64 (randNumeric 18)) (int64 (randNumeric 18)) ) | b64enc | quote }}
    {{- end }}
  {{- end }}
  databunker-masterkey: {{ $databunkerMasterkey }}

  {{- $databunkerRoottoken := "" }}
  {{- if $secret }}
    {{- if index $secret.data "databunker-roottoken" }}
      {{- $databunkerRoottoken = index $secret.data "databunker-roottoken" }}
    {{- end }}
  {{- end }}
  {{- if not $databunkerRoottoken }}
    {{- if .Values.databunkerRoottoken }}
      {{- $databunkerRoottoken = .Values.databunkerRoottoken | b64enc | quote }}
    {{- else }}
      {{- $databunkerRoottoken = uuidv4 | b64enc | quote }}
    {{- end }}
  {{- end }}
  databunker-roottoken: {{ $databunkerRoottoken }}
{{- end }}
