# run generate-env-files.sh to generate all key material, including root tocken.
version: '3'
services:
  mysql:
    image: mysql/mysql-server
    env_file:
      - .env/mysql-root.env
      - .env/mysql.env
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    command: --max_connections=2000
  # this container's job is to initialize MySQL database. It should run just one time.
  databunker-init:
    #build: .
    image: securitybunker/databunker:latest
    env_file:
      - .env/databunker.env
      - .env/databunker-root.env
    depends_on:
      - mysql
    entrypoint: /bin/sh
    command: -c "/databunker/bin/databunker -init -db databunkerdb"
  databunker:
    #build: .
    image: securitybunker/databunker:latest
    restart: unless-stopped
    env_file:
      - .env/databunker.env
    entrypoint: /bin/sh
    command: -c "/databunker/bin/databunker -db databunkerdb -conf /databunker/conf/databunker.yaml"
    depends_on:
      - mysql
    ports:
      - 3000:3000
